-- PetMarket Power BI Measures (DAX)
Total Products = SUM(category_summary[product_count])
Total Stock = SUM(category_summary[total_stock])
Inventory Value = SUM(category_summary[inventory_value])
Average Product Price = AVERAGE(category_summary[avg_price])
Average Rating = AVERAGE(category_summary[avg_rating])
Total Reviews = SUM(category_summary[total_reviews])
Total Orders = SUM(sales_summary[order_count])
Units Sold = SUM(sales_summary[units_sold])
Gross Sales = SUM(sales_summary[gross_sales])
Average Order Value = DIVIDE([Gross Sales], [Total Orders])
AI Training Rows = CALCULATE(SUM(ai_activity_summary[value]), ai_activity_summary[metric] = "chatbot_training_data")
